-- The Free Vault v4.5 — Catalog Quality & Admin Tools
-- Eseguire dopo la v4.4.
-- Tabelle leggere, RPC protette e trigger per preservare gli override catalogo.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('admin', 'moderator')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.catalog_overrides (
  match_key text primary key references public.catalog_games(match_key) on delete cascade,
  title text,
  canonical_title text,
  description text,
  developer text,
  publisher text,
  image_url text,
  store_url text,
  release_year integer,
  market_segment text check (market_segment is null or market_segment in ('aaa', 'indie', 'unclassified')),
  category_group text check (category_group is null or category_group in ('base_game', 'dlc', 'bundle', 'edition', 'other')),
  locked_fields text[] not null default '{}',
  updated_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moderation_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references auth.users(id) on delete cascade,
  target_type text not null check (target_type in ('review', 'comment', 'list')),
  target_id uuid not null,
  reason text not null check (char_length(reason) between 3 and 1000),
  status text not null default 'open' check (status in ('open', 'dismissed', 'removed')),
  resolution_note text check (resolution_note is null or char_length(resolution_note) <= 2000),
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists moderation_reports_open_unique
on public.moderation_reports(reporter_id, target_type, target_id)
where status = 'open';

create index if not exists moderation_reports_status_idx
on public.moderation_reports(status, created_at desc);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_idx
on public.admin_audit_log(created_at desc);

alter table public.canonical_match_queue
  add column if not exists reviewed_by uuid references auth.users(id) on delete set null,
  add column if not exists reviewed_at timestamptz,
  add column if not exists review_note text;

alter table public.admin_users enable row level security;
alter table public.catalog_overrides enable row level security;
alter table public.moderation_reports enable row level security;
alter table public.admin_audit_log enable row level security;

revoke all on public.admin_users from anon, authenticated;
revoke all on public.catalog_overrides from anon, authenticated;
revoke all on public.moderation_reports from anon, authenticated;
revoke all on public.admin_audit_log from anon, authenticated;

create or replace function public.current_admin_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select au.role
  from public.admin_users au
  where au.user_id = (select auth.uid())
  limit 1;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(public.current_admin_role() = 'admin', false);
$$;

create or replace function public.can_moderate()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(public.current_admin_role() in ('admin', 'moderator'), false);
$$;

revoke all on function public.current_admin_role() from public;
revoke all on function public.is_admin() from public;
revoke all on function public.can_moderate() from public;
grant execute on function public.current_admin_role() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.can_moderate() to authenticated;

create or replace function public.admin_context()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'role', public.current_admin_role(),
    'is_admin', public.is_admin(),
    'can_moderate', public.can_moderate()
  );
$$;

revoke all on function public.admin_context() from public;
grant execute on function public.admin_context() to authenticated;

create or replace function public.apply_catalog_override_to_row()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  o public.catalog_overrides%rowtype;
begin
  select * into o
  from public.catalog_overrides
  where match_key = new.match_key;

  if not found then
    return new;
  end if;

  if 'title' = any(o.locked_fields) and o.title is not null then new.title := o.title; end if;
  if 'canonical_title' = any(o.locked_fields) and o.canonical_title is not null then new.canonical_title := o.canonical_title; end if;
  if 'description' = any(o.locked_fields) and o.description is not null then new.description := o.description; end if;
  if 'developer' = any(o.locked_fields) and o.developer is not null then new.developer := o.developer; end if;
  if 'publisher' = any(o.locked_fields) and o.publisher is not null then new.publisher := o.publisher; end if;
  if 'image_url' = any(o.locked_fields) and o.image_url is not null then new.image_url := o.image_url; end if;
  if 'store_url' = any(o.locked_fields) and o.store_url is not null then new.store_url := o.store_url; end if;
  if 'release_year' = any(o.locked_fields) and o.release_year is not null then new.release_year := o.release_year; end if;
  if 'market_segment' = any(o.locked_fields) and o.market_segment is not null then new.market_segment := o.market_segment; end if;
  if 'category_group' = any(o.locked_fields) and o.category_group is not null then new.category_group := o.category_group; end if;

  return new;
end;
$$;

drop trigger if exists catalog_games_apply_override on public.catalog_games;
create trigger catalog_games_apply_override
before insert or update on public.catalog_games
for each row execute function public.apply_catalog_override_to_row();

create or replace function public.admin_get_catalog_record(p_key text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
set statement_timeout = '10s'
as $$
declare
  g public.catalog_games%rowtype;
  o public.catalog_overrides%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Accesso amministratore richiesto' using errcode = '42501';
  end if;

  select * into g
  from public.catalog_games
  where match_key = p_key or canonical_id = p_key
  order by case when match_key = p_key then 0 else 1 end
  limit 1;

  if not found then return null; end if;
  select * into o from public.catalog_overrides where match_key = g.match_key;

  return jsonb_build_object(
    'game', jsonb_build_object(
      'match_key', g.match_key,
      'canonical_id', g.canonical_id,
      'title', g.title,
      'canonical_title', g.canonical_title,
      'description', g.description,
      'developer', g.developer,
      'publisher', g.publisher,
      'image_url', g.image_url,
      'store_url', g.store_url,
      'release_year', g.release_year,
      'market_segment', g.market_segment,
      'category_group', g.category_group,
      'stores', g.stores,
      'store_listings', g.store_listings,
      'updated_at', g.updated_at
    ),
    'override', case when o.match_key is null then null else jsonb_build_object(
      'match_key', o.match_key,
      'title', o.title,
      'canonical_title', o.canonical_title,
      'description', o.description,
      'developer', o.developer,
      'publisher', o.publisher,
      'image_url', o.image_url,
      'store_url', o.store_url,
      'release_year', o.release_year,
      'market_segment', o.market_segment,
      'category_group', o.category_group,
      'locked_fields', o.locked_fields,
      'updated_at', o.updated_at
    ) end
  );
end;
$$;

create or replace function public.admin_save_catalog_override(
  p_match_key text,
  p_patch jsonb,
  p_locked_fields text[]
)
returns jsonb
language plpgsql
security definer
set search_path = ''
set statement_timeout = '10s'
as $$
declare
  allowed_fields constant text[] := array[
    'title','canonical_title','description','developer','publisher','image_url',
    'store_url','release_year','market_segment','category_group'
  ];
  locks text[];
  v_user uuid := (select auth.uid());
  segment_value text := nullif(btrim(p_patch ->> 'market_segment'), '');
  category_value text := nullif(btrim(p_patch ->> 'category_group'), '');
begin
  if not public.is_admin() then
    raise exception 'Accesso amministratore richiesto' using errcode = '42501';
  end if;
  if not exists (select 1 from public.catalog_games where match_key = p_match_key) then
    raise exception 'Gioco catalogo non trovato';
  end if;
  if exists (
    select 1 from unnest(coalesce(p_locked_fields, '{}'::text[])) f
    where not (f = any(allowed_fields))
  ) then
    raise exception 'Campo override non consentito';
  end if;

  select coalesce(array_agg(distinct f order by f), '{}'::text[])
  into locks
  from unnest(coalesce(p_locked_fields, '{}'::text[])) f;

  if segment_value is not null and segment_value not in ('aaa','indie','unclassified') then
    raise exception 'Segmento non valido';
  end if;
  if category_value is not null and category_value not in ('base_game','dlc','bundle','edition','other') then
    raise exception 'Categoria non valida';
  end if;

  insert into public.catalog_overrides (
    match_key, title, canonical_title, description, developer, publisher,
    image_url, store_url, release_year, market_segment, category_group,
    locked_fields, updated_by, updated_at
  ) values (
    p_match_key,
    nullif(btrim(p_patch ->> 'title'), ''),
    nullif(btrim(p_patch ->> 'canonical_title'), ''),
    nullif(btrim(p_patch ->> 'description'), ''),
    nullif(btrim(p_patch ->> 'developer'), ''),
    nullif(btrim(p_patch ->> 'publisher'), ''),
    nullif(btrim(p_patch ->> 'image_url'), ''),
    nullif(btrim(p_patch ->> 'store_url'), ''),
    case when p_patch ->> 'release_year' ~ '^[0-9]{4}$' then (p_patch ->> 'release_year')::integer else null end,
    segment_value,
    category_value,
    locks,
    v_user,
    now()
  )
  on conflict (match_key) do update set
    title = excluded.title,
    canonical_title = excluded.canonical_title,
    description = excluded.description,
    developer = excluded.developer,
    publisher = excluded.publisher,
    image_url = excluded.image_url,
    store_url = excluded.store_url,
    release_year = excluded.release_year,
    market_segment = excluded.market_segment,
    category_group = excluded.category_group,
    locked_fields = excluded.locked_fields,
    updated_by = excluded.updated_by,
    updated_at = now();

  update public.catalog_games
  set updated_at = now()
  where match_key = p_match_key;

  insert into public.admin_audit_log(actor_id, action, target_type, target_id, metadata)
  values (v_user, 'catalog_override_saved', 'catalog_game', p_match_key, jsonb_build_object('locked_fields', locks));

  return public.admin_get_catalog_record(p_match_key);
end;
$$;

create or replace function public.admin_clear_catalog_override(p_match_key text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
begin
  if not public.is_admin() then
    raise exception 'Accesso amministratore richiesto' using errcode = '42501';
  end if;
  delete from public.catalog_overrides where match_key = p_match_key;
  insert into public.admin_audit_log(actor_id, action, target_type, target_id)
  values (v_user, 'catalog_override_cleared', 'catalog_game', p_match_key);
  return jsonb_build_object('ok', true, 'message', 'Override rimosso. I dati automatici torneranno al prossimo sync.');
end;
$$;

create or replace function public.admin_list_match_queue(
  p_status text default 'pending',
  p_limit integer default 50,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
set statement_timeout = '10s'
as $$
declare
  result jsonb;
begin
  if not public.is_admin() then
    raise exception 'Accesso amministratore richiesto' using errcode = '42501';
  end if;
  if p_status not in ('pending','verified','rejected','all') then raise exception 'Stato non valido'; end if;

  with filtered as materialized (
    select q.*
    from public.canonical_match_queue q
    where p_status = 'all' or q.status = p_status
  ), page as (
    select * from filtered
    order by case when status = 'pending' then 0 else 1 end, confidence desc, created_at desc
    limit greatest(1, least(coalesce(p_limit, 50), 100))
    offset greatest(coalesce(p_offset, 0), 0)
  )
  select jsonb_build_object(
    'items', coalesce((select jsonb_agg(to_jsonb(page) order by confidence desc, created_at desc) from page), '[]'::jsonb),
    'total', (select count(*) from filtered)
  ) into result;
  return result;
end;
$$;

create or replace function public.admin_review_match(
  p_id uuid,
  p_status text,
  p_resolved_game_id text default null,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  updated_row public.canonical_match_queue%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Accesso amministratore richiesto' using errcode = '42501';
  end if;
  if p_status not in ('verified','rejected','pending') then raise exception 'Stato non valido'; end if;

  update public.canonical_match_queue
  set status = p_status,
      resolved_game_id = case when p_status = 'verified' then p_resolved_game_id else null end,
      review_note = nullif(btrim(p_note), ''),
      reviewed_by = v_user,
      reviewed_at = now(),
      updated_at = now()
  where id = p_id
  returning * into updated_row;

  if not found then raise exception 'Candidato non trovato'; end if;
  insert into public.admin_audit_log(actor_id, action, target_type, target_id, metadata)
  values (v_user, 'catalog_match_reviewed', 'canonical_match', p_id::text, jsonb_build_object('status', p_status));
  return to_jsonb(updated_row);
end;
$$;

create or replace function public.report_content(
  p_target_type text,
  p_target_id uuid,
  p_reason text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  existing_id uuid;
  new_id uuid;
begin
  if v_user is null then raise exception 'Accedi per inviare una segnalazione' using errcode = '42501'; end if;
  if p_target_type not in ('review','comment','list') then raise exception 'Tipo contenuto non valido'; end if;
  if char_length(btrim(coalesce(p_reason, ''))) < 3 then raise exception 'Descrivi brevemente il problema'; end if;

  if p_target_type = 'review' and not exists (select 1 from public.game_reviews where id = p_target_id) then raise exception 'Recensione non trovata'; end if;
  if p_target_type = 'comment' and not exists (select 1 from public.content_comments where id = p_target_id) then raise exception 'Commento non trovato'; end if;
  if p_target_type = 'list' and not exists (select 1 from public.user_lists where id = p_target_id) then raise exception 'Lista non trovata'; end if;

  select id into existing_id
  from public.moderation_reports
  where reporter_id = v_user and target_type = p_target_type and target_id = p_target_id and status = 'open'
  limit 1;
  if existing_id is not null then return existing_id; end if;

  insert into public.moderation_reports(reporter_id, target_type, target_id, reason)
  values (v_user, p_target_type, p_target_id, left(btrim(p_reason), 1000))
  returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.admin_list_reports(
  p_status text default 'open',
  p_limit integer default 50,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
set statement_timeout = '10s'
as $$
declare
  result jsonb;
begin
  if not public.can_moderate() then
    raise exception 'Permesso moderazione richiesto' using errcode = '42501';
  end if;
  if p_status not in ('open','dismissed','removed','all') then raise exception 'Stato non valido'; end if;

  with filtered as materialized (
    select r.*
    from public.moderation_reports r
    where p_status = 'all' or r.status = p_status
  ), enriched as (
    select
      f.*,
      p.username as reporter_username,
      p.display_name as reporter_display_name,
      case
        when f.target_type = 'review' then (
          select jsonb_build_object('label', gr.game_title, 'body', gr.body, 'author_id', gr.user_id)
          from public.game_reviews gr where gr.id = f.target_id
        )
        when f.target_type = 'comment' then (
          select jsonb_build_object('label', 'Commento', 'body', cc.body, 'author_id', cc.user_id)
          from public.content_comments cc where cc.id = f.target_id
        )
        when f.target_type = 'list' then (
          select jsonb_build_object('label', ul.name, 'body', ul.description, 'author_id', ul.user_id)
          from public.user_lists ul where ul.id = f.target_id
        )
      end as target
    from filtered f
    left join public.profiles p on p.id = f.reporter_id
    order by f.created_at desc
    limit greatest(1, least(coalesce(p_limit, 50), 100))
    offset greatest(coalesce(p_offset, 0), 0)
  )
  select jsonb_build_object(
    'items', coalesce((select jsonb_agg(to_jsonb(enriched) order by created_at desc) from enriched), '[]'::jsonb),
    'total', (select count(*) from filtered)
  ) into result;
  return result;
end;
$$;

create or replace function public.admin_resolve_report(
  p_report_id uuid,
  p_action text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  r public.moderation_reports%rowtype;
begin
  if not public.can_moderate() then
    raise exception 'Permesso moderazione richiesto' using errcode = '42501';
  end if;
  if p_action not in ('dismiss','remove') then raise exception 'Azione non valida'; end if;

  select * into r from public.moderation_reports where id = p_report_id for update;
  if not found then raise exception 'Segnalazione non trovata'; end if;

  if p_action = 'remove' then
    if r.target_type = 'review' then
      delete from public.content_comments where target_type = 'review' and target_id = r.target_id;
      delete from public.game_reviews where id = r.target_id;
    elsif r.target_type = 'comment' then
      delete from public.content_comments where id = r.target_id;
    elsif r.target_type = 'list' then
      delete from public.content_comments where target_type = 'list' and target_id = r.target_id;
      delete from public.user_lists where id = r.target_id;
    end if;
  end if;

  update public.moderation_reports
  set status = case when p_action = 'remove' then 'removed' else 'dismissed' end,
      resolution_note = nullif(btrim(p_note), ''),
      resolved_by = v_user,
      resolved_at = now(),
      updated_at = now()
  where id = p_report_id
  returning * into r;

  insert into public.admin_audit_log(actor_id, action, target_type, target_id, metadata)
  values (v_user, 'moderation_' || p_action, r.target_type, r.target_id::text, jsonb_build_object('report_id', r.id));
  return to_jsonb(r);
end;
$$;

create or replace function public.admin_system_status()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
set statement_timeout = '10s'
as $$
declare
  stats jsonb;
  sync_rows jsonb;
begin
  if not public.is_admin() then
    raise exception 'Accesso amministratore richiesto' using errcode = '42501';
  end if;

  select coalesce(jsonb_agg(to_jsonb(s) order by s.store), '[]'::jsonb)
  into sync_rows
  from public.catalog_sync_state s;

  select jsonb_build_object(
    'database_size_bytes', pg_database_size(current_database()),
    'catalog_size_bytes', pg_total_relation_size('public.catalog_games'::regclass),
    'catalog_games', coalesce(c.total_games, 0),
    'catalog_listings', coalesce(c.total_listings, 0),
    'catalog_status', coalesce(c.status, 'unknown'),
    'catalog_updated_at', c.updated_at,
    'open_reports', (select count(*) from public.moderation_reports where status = 'open'),
    'pending_matches', (select count(*) from public.canonical_match_queue where status = 'pending'),
    'sync', sync_rows
  ) into stats
  from public.catalog_stats_cache c
  where c.singleton;

  if stats is null then
    stats := jsonb_build_object(
      'database_size_bytes', pg_database_size(current_database()),
      'catalog_size_bytes', pg_total_relation_size('public.catalog_games'::regclass),
      'catalog_games', 0,
      'catalog_listings', 0,
      'catalog_status', 'unknown',
      'open_reports', (select count(*) from public.moderation_reports where status = 'open'),
      'pending_matches', (select count(*) from public.canonical_match_queue where status = 'pending'),
      'sync', sync_rows
    );
  end if;
  return stats;
end;
$$;

revoke all on function public.admin_get_catalog_record(text) from public;
revoke all on function public.admin_save_catalog_override(text,jsonb,text[]) from public;
revoke all on function public.admin_clear_catalog_override(text) from public;
revoke all on function public.admin_list_match_queue(text,integer,integer) from public;
revoke all on function public.admin_review_match(uuid,text,text,text) from public;
revoke all on function public.report_content(text,uuid,text) from public;
revoke all on function public.admin_list_reports(text,integer,integer) from public;
revoke all on function public.admin_resolve_report(uuid,text,text) from public;
revoke all on function public.admin_system_status() from public;

grant execute on function public.admin_get_catalog_record(text) to authenticated;
grant execute on function public.admin_save_catalog_override(text,jsonb,text[]) to authenticated;
grant execute on function public.admin_clear_catalog_override(text) to authenticated;
grant execute on function public.admin_list_match_queue(text,integer,integer) to authenticated;
grant execute on function public.admin_review_match(uuid,text,text,text) to authenticated;
grant execute on function public.report_content(text,uuid,text) to authenticated;
grant execute on function public.admin_list_reports(text,integer,integer) to authenticated;
grant execute on function public.admin_resolve_report(uuid,text,text) to authenticated;
grant execute on function public.admin_system_status() to authenticated;

comment on table public.catalog_overrides is 'Override editoriali persistenti rispettati dai sync catalogo.';
comment on table public.moderation_reports is 'Segnalazioni utente per recensioni, commenti e liste.';
comment on function public.admin_system_status() is 'Dashboard tecnica leggera senza scansioni complete del catalogo.';
